language: php
php:
  - 5.5
  - 5.6
  - nightly
  # - 5.4
  # - hhvm

before_script:
  - composer install --dev
  - mkdir -p build/logs

script:
 - vendor/codeception/codeception/codecept run 
 - phpunit --coverage-clover build/logs/clover.xml

after_script:
 - php vendor/bin/coveralls -v

# matrix:
#   allow_failures:
#     - php: hhvm
